import type { NextPage } from 'next';
import Head from 'next/head';
import type { inferProcedureOutput } from '@trpc/server';
import type { AppRouter } from '@podium/api';
import { trpc } from '../utils/trpc';
import { withAuth } from '@/components/auth/WithAuth';

const ExerciseCard: React.FC<{
  exercise: inferProcedureOutput<AppRouter['exercises']['all']>[number];
}> = ({ exercise }) => {
  return (
    <div className="p-4 ">
      <h2 className="text-2xl font-bold text-gray-800">{exercise.name}</h2>
      <p className="text-gray-600">{exercise.category}</p>
    </div>
  );
};

const Home: NextPage = () => {
  const exerciseQuery = trpc.exercises.all.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {exerciseQuery.data ? (
            <div className="flex flex-col gap-4">
              {exerciseQuery.data?.map((p) => {
                return <ExerciseCard key={p.id} exercise={p} />;
              })}
            </div>
          ) : (
            <p>Loading..</p>
          )}
        </div>
      </main>
    </>
  );
};

export default withAuth(Home);
