import 'react-native-get-random-values';
import { v4 as uuidv4 } from 'uuid';
import { createStore, useStore } from 'zustand';
import { immer } from 'zustand/middleware/immer';
import produce from 'immer';
import { createContext, useCallback, useContext, useRef } from 'react';
import type { Exercise, TemplateExerciseWithExercise, TemplateSet, TemplateWithExercisesAndSets } from '@podium/db';

import { useFocusEffect } from '@react-navigation/native';
import type {
  TemplateCreate,
  TemplateExerciseCreate,
  TemplateExerciseUpdate,
  TemplateSetCreate,
  TemplateSetUpdate,
  TemplateUpdate,
} from '@podium/api';
import { getAuthSafeUser } from '@/stores/global/auth';
import { trpc } from '@/trpc';

type ExerciseId = string;
type TemplateId = string;
type TemplateExerciseId = string;
type TemplateSetId = string;

type Position = number;

type TemplateExerciseNew = Omit<TemplateExerciseCreate, 'position'> & { exercise: Exercise };
type TemplateExerciseUpdated = TemplateExerciseUpdate;

type TemplateSetNew = Omit<TemplateSetCreate, 'position'>;
type TemplateSetUpdated = TemplateSetUpdate;

type TemplateExercisePositions = Record<TemplateExerciseId, Position>;
type TemplateSetPositions = Record<TemplateExerciseId, Record<TemplateSetId, Position>>;

interface TemplateStoreProps {
  id: TemplateId;
  name: string;
  templateExercises: TemplateExerciseWithExercise[];
  templateSets: TemplateSet[];
  isLoading: boolean;
  isError: boolean;
}

interface TemplateStoreState {
  id: TemplateId;
  name: string;
  changed: { name: boolean };

  isNew: boolean;
  isLoading: boolean;
  isError: boolean;

  templateExercises: {
    /** An array of all the template exercises that currently exist in the db for this template and haven't been modified by the user */
    existing: Record<TemplateExerciseId, TemplateExerciseWithExercise>;
    /** An object of all the new template exercises created  */
    new: Record<TemplateExerciseId, TemplateExerciseNew>;
    /** An object of all the existing template exercises that have been modified */
    updated: Record<TemplateExerciseId, TemplateExerciseUpdated>;
    /** An array of all the template exercise ids which currently exist in the db but the user has deleted but not submitted yet. */
    deleted: Array<TemplateExerciseId>;
    /** An object of the current positions of all the exercises */
    positions: TemplateExercisePositions;
    /** Useful filters to help access specific template exercises quicker */
    filters: {
      /** An object of exercise ids and the array of template exercise ids that relate to it */
      byExerciseId: Record<ExerciseId, Array<TemplateExerciseId>>;
    };
  };
  templateSets: {
    /** An array of all the template sets that currently exist in the db for this template and haven't been modified by the user */
    existing: Record<TemplateSetId, TemplateSet>;
    /** An object of all the new template sets created  */
    new: Record<TemplateSetId, TemplateSetNew>;
    /** An object of all the existing template sets that have been modified */
    updated: Record<TemplateSetId, TemplateSetUpdated>;
    /** An array of all the template set ids which currently exist in the db but the user has deleted but not submitted yet. */
    deleted: Array<TemplateSetId>;
    /** An object of the current order of the template sets grouped by their template exercise id */
    positions: TemplateSetPositions;
    /** Useful filters to help access specific template sets quicker */
    filters: {
      /** An object of template exercise ids and the array of template set ids that relate to it */
      byTemplateExerciseId: Record<TemplateExerciseId, Array<TemplateSetId>>;
    };
  };
}

interface TemplateStoreAPI {
  api: {
    // Template Info
    /** Pass the updated template name to set it within the template store */
    setName(name: string): void;

    // Template Exercises
    /** Add a new template exercise by passing an exercise id which the new template exercise will be generated by */
    addTemplateExercise(exerciseId: Exercise): void;
    /** Update certain properties of the template exercise */
    updateTemplateExercise(updatedTemplateExercise: TemplateExerciseUpdate): void;
    /** Remove a template exercise and it's template sets by passing the template exercise id */
    removeTemplateExercise(templateExerciseId: TemplateExerciseId): void;
    /** Pass the updated positions to set the positions for the template exercises  */
    syncTemplateExercisePositions(positions: TemplateExercisePositions): void;

    // Template Sets
    /** Add a new template set by passing the template exercise id which the new template set will be generated by */
    addTemplateSet(templateExerciseId: TemplateExerciseId): void;
    /** Update certain properties of the template set */
    updateTemplateSet(updatedTemplateSet: TemplateSetUpdate): void;
    /** Remove a template set by passing the template set id */
    removeTemplateSet(templateSetId: TemplateSetId): void;

    // Utils
    /** Returns a template object that is formatted correctly for submission */
    getSubmittableTemplate(): TemplateCreate | TemplateUpdate;
  };
}

type TemplateStore = TemplateStoreState & TemplateStoreAPI;

const createTemplateStore = (initProps?: Partial<TemplateStoreProps>) => {
  let DEFAULT_PROPS: TemplateStoreState = {
    id: initProps?.id || uuidv4(),
    name: initProps?.name || 'Legs 1',
    changed: { name: false },

    isNew: !initProps?.id,
    isLoading: initProps?.isLoading || false,
    isError: initProps?.isError || false,

    templateExercises: {
      existing: {},
      new: {},
      updated: {},
      deleted: [],
      positions: {},
      filters: { byExerciseId: {} },
    },
    templateSets: {
      existing: {},
      new: {},
      updated: {},
      deleted: [],
      positions: {},
      filters: { byTemplateExerciseId: {} },
    },
  };

  DEFAULT_PROPS = produce(DEFAULT_PROPS, (draft) => {
    if (initProps?.templateExercises) {
      const sortedTemplateExercises = initProps.templateExercises.sort((a, b) => a.position - b.position);
      for (let i = 0; i < sortedTemplateExercises.length; i++) {
        const { position, ...templateExercise } = sortedTemplateExercises[i]!;

        // Add template exercise to the existing object
        draft.templateExercises.existing[templateExercise.id] = { ...templateExercise, position: i };

        const { id, exerciseId } = templateExercise;

        // Add template exercise to it's byExerciseId filter
        if (!draft.templateExercises.filters.byExerciseId[exerciseId]) {
          draft.templateExercises.filters.byExerciseId[exerciseId] = [];
        }
        draft.templateExercises.filters.byExerciseId[exerciseId]?.push(id);

        // Add the position of the existing template exercise, ensuring the position is correct
        draft.templateExercises.positions[id] = i;

        // If position is incorrect, add it to the updated template exercises to be fixed
        if (position !== i) draft.templateExercises.updated[id] = { id, position: i };
      }
    }
    if (initProps?.templateSets) {
      for (const templateSet of initProps.templateSets) {
        // Add template set to the existing object
        draft.templateSets.existing[templateSet.id] = templateSet;

        const { id, templateExerciseId, position } = templateSet;

        // Add template set to it's byTemplateExerciseId object
        if (!draft.templateSets.filters.byTemplateExerciseId[templateExerciseId]) {
          draft.templateSets.filters.byTemplateExerciseId[templateExerciseId] = [];
        }
        draft.templateSets.filters.byTemplateExerciseId[templateExerciseId]?.push(id);

        // Add the position of the template set
        if (!draft.templateSets.positions[templateExerciseId]) {
          draft.templateSets.positions[templateExerciseId] = {};
        }
        draft.templateSets.positions[templateExerciseId]![id] = position;
      }
    }
  });

  return createStore(
    immer<TemplateStore>((set, get) => ({
      ...DEFAULT_PROPS,

      api: {
        // Template Info
        setName: (name) =>
          set((template) => {
            template.name = name;
            if (!template.changed.name) template.changed.name = true;
          }),

        // Template Exercises
        addTemplateExercise: (exercise) => {
          const templateExerciseId = uuidv4();
          set((template) => {
            const user = getAuthSafeUser();
            const { id: exerciseId } = exercise;

            const templateExercise: TemplateExerciseNew = {
              id: templateExerciseId,
              exerciseId,
              templateId: template.id,
              notes: '',
              userId: user.id,
              exercise,
            };

            // Add the Template Exercise id to the byExerciseId object
            if (!template.templateExercises.filters.byExerciseId[exerciseId]) {
              template.templateExercises.filters.byExerciseId[exerciseId] = [];
            }
            template.templateExercises.filters.byExerciseId[exerciseId]?.push(templateExercise.id);

            // Add the Template Exercise to the new Template Exercises object.
            template.templateExercises.new[templateExercise.id] = templateExercise;

            // Add Template Exercise to positions
            template.templateExercises.positions[templateExercise.id] = Object.keys(
              template.templateExercises.positions,
            ).length;
          });

          // Create 3 sets for the new exercise
          for (let i = 0; i < 1; i++) {
            get().api.addTemplateSet(templateExerciseId);
          }
        },
        updateTemplateExercise: (updatedTemplateExercise) =>
          set((template) => {
            const { id, ...changes } = updatedTemplateExercise;
            // Is existing
            if (template.templateExercises.existing[id]) {
              template.templateExercises.updated[id] = { id, ...changes };
            }
            // Is new
            if (template.templateExercises.new[id]) {
              template.templateExercises.new[id] = {
                ...template.templateExercises.new[id]!,
                ...changes,
              };
            }
            // is updated
            if (template.templateExercises.updated[id]) {
              template.templateExercises.updated[id] = {
                ...template.templateExercises.updated[id]!,
                ...changes,
              };
            }
          }),
        removeTemplateExercise: (templateExerciseId) => {
          set((template) => {
            // Is Existing
            if (template.templateExercises.existing[templateExerciseId]) {
              delete template.templateExercises.existing[templateExerciseId];
              template.templateExercises.deleted.push(templateExerciseId);
            }
            // Is new
            if (template.templateExercises.new[templateExerciseId]) {
              const exerciseId = template.templateExercises.new[templateExerciseId]!.exerciseId;
              delete template.templateExercises.new[templateExerciseId];
              template.templateExercises.filters.byExerciseId[exerciseId] =
                template.templateExercises.filters.byExerciseId[exerciseId]!.filter((id) => id !== templateExerciseId);
            }
            // Is Updated
            if (template.templateExercises.updated[templateExerciseId]) {
              delete template.templateExercises.updated[templateExerciseId];
              template.templateExercises.deleted.push(templateExerciseId);
            }

            // Remove template exercise from Template Exercise positions
            const newPositions: TemplateExercisePositions = {};
            const swapped = Object.entries(template.templateExercises.positions).map(([key, value]) => [value, key]);
            const ids = swapped
              .sort()
              .map(([_, value]) => value as string)
              .filter((id) => id !== templateExerciseId);

            ids.forEach((id, index) => {
              newPositions[id] = index;
            });
            template.templateExercises.positions = newPositions;
          });

          // Remove the template sets associated with this template exercise
          const templateExerciseSetIds = get().templateSets.filters.byTemplateExerciseId[templateExerciseId] ?? null;
          if (templateExerciseSetIds) {
            for (const templateSetId of templateExerciseSetIds) {
              get().api.removeTemplateSet(templateSetId);
            }
          }
        },
        syncTemplateExercisePositions: (positions) =>
          set((template) => {
            template.templateExercises.positions = positions;
          }),

        // Template Sets
        addTemplateSet: (templateExerciseId) =>
          set((template) => {
            const user = getAuthSafeUser();
            const templateSet: TemplateSetNew = {
              id: uuidv4(),
              templateId: template.id,
              templateExerciseId,
              type: 'working',
              reps: '',
              userId: user.id,
            };

            // Add the Template Set id to the byTemplateExerciseId object
            if (!template.templateSets.filters.byTemplateExerciseId[templateExerciseId]) {
              template.templateSets.filters.byTemplateExerciseId[templateExerciseId] = [];
            }
            template.templateSets.filters.byTemplateExerciseId[templateExerciseId]?.push(templateSet.id);

            // Add the Template Set to the new Template Sets object.
            template.templateSets.new[templateSet.id] = templateSet;

            // Add the new template set to the positions object of its template exercise
            if (!template.templateSets.positions[templateExerciseId]) {
              template.templateSets.positions[templateExerciseId] = {};
            }
            template.templateSets.positions[templateExerciseId]![templateSet.id] = Object.keys(
              template.templateSets.positions[templateExerciseId]!,
            ).length;
          }),
        updateTemplateSet: (updatedTemplateSet) =>
          set((template) => {
            const { id, ...changes } = updatedTemplateSet;
            // Is Existing
            if (template.templateSets.existing[id]) {
              template.templateSets.updated[id] = { id, ...changes };
            }
            // Is new
            if (template.templateSets.new[id]) {
              template.templateSets.new[id] = {
                ...template.templateSets.new[id]!,
                ...changes,
              };
            }
            // Is updated
            if (template.templateSets.updated[id]) {
              template.templateSets.updated[id] = {
                ...template.templateSets.updated[id]!,
                ...changes,
              };
            }
          }),
        removeTemplateSet: (templateSetId) =>
          set((template) => {
            // Is existing
            if (template.templateSets.existing[templateSetId]) {
              delete template.templateSets.existing[templateSetId];
              template.templateSets.deleted.push(templateSetId);
            }
            // Is new
            if (template.templateSets.new[templateSetId]) {
              const templateExerciseId = template.templateSets.new[templateSetId]!.templateExerciseId;
              delete template.templateSets.new[templateSetId];
              const templateExerciseSetFilter = template.templateSets.filters.byTemplateExerciseId[templateExerciseId];
              if (templateExerciseSetFilter) {
                template.templateSets.filters.byTemplateExerciseId[templateExerciseId] =
                  templateExerciseSetFilter!.filter((id) => id !== templateSetId);
              }
            }
            // Is updated
            if (template.templateSets.updated[templateSetId]) {
              delete template.templateSets.updated[templateSetId];
              template.templateSets.deleted.push(templateSetId);
            }

            // Update all the template set positions of the same template exercise
            Object.entries(template.templateSets.positions).every(([templateExerciseId, templateSetPositions]) => {
              if (templateSetPositions[templateSetId] != null) {
                const newPositions: Record<TemplateSetId, Position> = {};
                const swapped = Object.entries(templateSetPositions).map(([key, value]) => [value, key]);
                const ids = swapped
                  .sort()
                  .map(([_, value]) => value as string)
                  .filter((id) => id !== templateSetId);
                ids.forEach((id, index) => {
                  newPositions[id] = index;
                });
                template.templateSets.positions[templateExerciseId] = newPositions;
                return false;
              }
              return true;
            });
          }),

        // Utils
        getSubmittableTemplate: () => {
          const userId = getAuthSafeUser().id;
          const template = get();

          // Template Exercises
          const templateExercisesNew: TemplateUpdate['templateExercises']['new'] = [];

          for (const templateExerciseId in template.templateExercises.new) {
            const templateExercise = template.templateExercises.new[templateExerciseId]!;
            const position = template.templateExercises.positions[templateExerciseId];
            if (position != null) {
              templateExercisesNew.push({
                ...templateExercise,
                position,
              });
            }
          }

          // Template Sets
          const templateSetsNew: TemplateUpdate['templateSets']['new'] = [];

          for (const templateSetId in template.templateSets.new) {
            const templateSet = template.templateSets.new[templateSetId]!;
            const position = template.templateSets.positions[templateSet.templateExerciseId]![templateSetId];
            if (position != null) {
              templateSetsNew.push({
                ...templateSet,
                position,
              });
            }
          }

          if (template.isNew) {
            const templateCreate: TemplateCreate = {
              id: template.id,
              name: template.name,
              userId,
              templateExercises: templateExercisesNew,
              templateSets: templateSetsNew,
            };
            return templateCreate;
          }

          const templateExercisePositionChanged: TemplateUpdate['templateExercises']['updated'] = [];

          // Check if the position has been changed on any of the existing template exercises
          for (const templateExerciseId in template.templateExercises.existing) {
            const templateExercise = template.templateExercises.existing[templateExerciseId]!;
            const position = template.templateExercises.positions[templateExerciseId];
            if (position != null && position !== templateExercise.position) {
              templateExercisePositionChanged.push({ id: templateExercise.id, position });
            }
          }

          const templateUpdate: TemplateUpdate = {
            id: template.id,
            name: template.changed.name ? template.name : undefined,
            userId,
            templateExercises: {
              new: templateExercisesNew,
              updated: Object.values(template.templateExercises.updated).concat(templateExercisePositionChanged),
              deleted: template.templateExercises.deleted,
            },
            templateSets: {
              new: templateSetsNew,
              updated: Object.values(template.templateSets.updated),
              deleted: template.templateSets.deleted,
            },
          };
          return templateUpdate;
        },
      },
    })),
  );
};

type CreatedTemplateStore = ReturnType<typeof createTemplateStore>;

const TemplateContext = createContext<CreatedTemplateStore | null>(null);

function useTemplateContext<T>(selector: (state: TemplateStore) => T, equalityFn?: (left: T, right: T) => boolean): T {
  const store = useContext(TemplateContext);
  if (!store) {
    throw new Error(
      // eslint-disable-next-line @typescript-eslint/quotes
      "[Template Context] A component tried to use Template Context without being a child of a TemplateProvider or TemplateProvider's store has not been initialized yet. Please fix this",
    );
  }
  return useStore(store, selector, equalityFn);
}

interface TemplateProviderProps {
  template: TemplateWithExercisesAndSets | null;
  isLoading: boolean;
}

export function TemplateProvider({ children, template, isLoading }: React.PropsWithChildren<TemplateProviderProps>) {
  const storeRef = useRef<CreatedTemplateStore>();

  useFocusEffect(
    useCallback(() => {
      return () => {
        // @ts-expect-error - This is a hack to reset the store
        storeRef.current?.setState(null);
        storeRef.current = undefined;
      };
    }, []),
  );

  if (!storeRef.current && !isLoading) {
    storeRef.current = createTemplateStore(
      template
        ? {
            id: template.id,
            name: template.name,
            templateExercises: template.templateExercises,
            templateSets: template.templateSets,
          }
        : {},
    );
  }

  return <TemplateContext.Provider value={storeRef.current || null}>{children}</TemplateContext.Provider>;
}

export const useTemplateAPI = () => useTemplateContext((s) => s.api);

// Template Info
export const useTemplateId = () => useTemplateContext((s) => s.id);
export const useTemplateName = () => useTemplateContext((s) => s.name);
export const useTemplateIsNew = () => useTemplateContext((s) => s.isNew);
export const useTemplateIsLoading = () => useTemplateContext((s) => s.isLoading);
export const useTemplateIsError = () => useTemplateContext((s) => s.isError);

// Template Exercise
/** Returns an array of all the template exercise ids in order of their positions */
export function useTemplateExerciseIds() {
  const positions = useTemplateContext((s) => s.templateExercises.positions);
  const swapped = Object.entries(positions).map(([key, value]) => [value, key]);
  const ids = swapped.sort().map(([_, value]) => value as string);
  return ids;
}
/** Returns all the given template sets that relate to the provided exercise id */
export function useTemplateExerciseIdsByExerciseId(exerciseId: ExerciseId): TemplateExerciseId[] | null {
  const templateExercises = useTemplateContext((s) => s.templateExercises.filters.byExerciseId[exerciseId] ?? null);
  return templateExercises;
}

/** Returns the full template exercise of the given template exercise id or null if that id does not exist */
export function useTemplateExercise(templateExerciseId: TemplateExerciseId) {
  const existingTemplateExercise: TemplateExerciseWithExercise | null = useTemplateContext(
    (s) => s.templateExercises.existing[templateExerciseId] ?? null,
  );
  const newTemplateExercise: TemplateExerciseNew | null = useTemplateContext(
    (s) => s.templateExercises.new[templateExerciseId] ?? null,
  );
  const updatedTemplateExercise: TemplateExerciseUpdated | null = useTemplateContext(
    (s) => s.templateExercises.updated[templateExerciseId] ?? null,
  );

  const {
    data: exercise,
    isLoading: isExerciseLoading,
    isError: isExerciseError,
  } = trpc.exercise.byId.useQuery(
    { id: newTemplateExercise?.exerciseId as string },
    { enabled: !!newTemplateExercise },
  );

  // If it's existing but has been updated
  if (updatedTemplateExercise && existingTemplateExercise) {
    return {
      templateExercise: {
        ...existingTemplateExercise,
        ...updatedTemplateExercise,
      },
      isLoading: false,
      isError: false,
    };
  }

  // If it's existing and has not been updated
  if (existingTemplateExercise != null) {
    return {
      templateExercise: existingTemplateExercise,
      isLoading: false,
      isError: false,
    };
  }

  // If it's new template exercise
  if (newTemplateExercise) {
    return {
      templateExercise: {
        ...newTemplateExercise,
        exercise,
      },
      isLoading: isExerciseLoading,
      isError: isExerciseError,
    };
  }

  // If an invalid/non existent id has been passed
  return { templateExercise: null, isLoading: false, isError: true };
}

/** Returns the template exercise positions object from the store */
export const useTemplateExercisePositions = () => useTemplateContext((s) => s.templateExercises.positions);

// Template Sets
/** Returns the template sets for the given template exercise id in order of their position */
export function useTemplateSetIdsByTemplateExerciseId(templateExerciseId: TemplateExerciseId): TemplateSetId[] | null {
  const positions = useTemplateContext((s) => s.templateSets.positions[templateExerciseId] ?? null);
  if (!positions) return null;
  const swapped = Object.entries(positions).map(([key, value]) => [value, key]);
  const ids = swapped.sort().map(([_, value]) => value as string);
  return ids;
}

/** Returns the full template set or null if that id does not exist  */
export function useTemplateSet(templateSetId: TemplateSetId) {
  const existingTemplateSet: TemplateSet | null = useTemplateContext(
    (s) => s.templateSets.existing[templateSetId] ?? null,
  );
  const newTemplateSet: TemplateSetNew | null = useTemplateContext((s) => s.templateSets.new[templateSetId] ?? null);
  const updatedTemplateSet: TemplateSetUpdated | null = useTemplateContext(
    (s) => s.templateSets.updated[templateSetId] ?? null,
  );

  // If it's existing but has been updated
  if (updatedTemplateSet && existingTemplateSet) {
    return {
      templateSet: {
        ...existingTemplateSet,
        ...updatedTemplateSet,
      },

      isLoading: false,
      isError: false,
    };
  }

  // If it's existing and has not been updated
  if (existingTemplateSet) {
    return {
      templateSet: existingTemplateSet,
      isLoading: false,
      isError: false,
    };
  }

  // If it's  new
  if (newTemplateSet) {
    return {
      templateSet: newTemplateSet,
      isLoading: false,
      isError: false,
    };
  }
  // Improper Id Passed
  return { templateSet: null, isLoading: false, isError: true };
}
