import 'react-native-get-random-values';
import { v4 as uuidv4 } from 'uuid';
import { createContext, useCallback, useContext, useRef } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import { createStore, useStore } from 'zustand';
import { immer } from 'zustand/middleware/immer';
import produce from 'immer';
import type { Exercise, TemplateExerciseWithExercise, TemplateSet, TemplateWithExercisesAndSets } from '@podium/db';
import type { TemplateCreate, TemplateExerciseUpdate, TemplateSetUpdate, TemplateUpdate } from '@podium/api';

import { getAuthSafeUser } from '../global/AuthProvider';

interface TemplateStoreProps {
  id: string;
  name: string;
  templateExercises: TemplateExerciseWithExercise[];
  templateSets: TemplateSet[];
}

interface TemplateStoreState {
  id: string;
  name: string;
  changed: { name: boolean };

  isNew: boolean;

  templateExercises: {
    /** An object with all the template exercises, including those currently existing in the db and any updated yet to be saved, as well as any newly created exercises */
    all: Record<string, TemplateExerciseWithExercise>;
    /** An array of the template exercise ids that exist in the db  */
    existing: Set<string>;
    /** An array of the template exercise ids that are new  */
    new: Set<string>;
    /** An array of the template exercise ids that have been updated */
    updated: Set<string>;
    /** An array of all the template exercise ids that currently exist in the db but have been deleted but not saved yet */
    deleted: Set<string>;
    /** Useful filters to help access specific template exercises quicker */
    filters: {
      /** An object of exercise ids and the array of template exercise ids that relate to it */
      byExerciseId: Record<string, Set<string>>;
    };
  };
  templateSets: {
    /** An object with all the template sets, including those currently existing in the db and any updated yet to be saved, as well as any newly created sets */
    all: Record<string, TemplateSet>;
    /** An array of the template set ids that exist in the db  */
    existing: Set<string>;
    /** An array of the template set ids that are new  */
    new: Set<string>;
    /** An array of the template set ids that have been updated */
    updated: Set<string>;
    /** An array of all the template set ids that currently exist in the db but have been deleted but not saved yet */
    deleted: Set<string>;
    /** Useful filters to help access specific template sets quicker */
    filters: {
      /** An object of template exercise ids and the array of template set ids that relate to it */
      byTemplateExerciseId: Record<string, Set<string>>;
    };
  };
}

interface TemplateStoreAPI {
  api: {
    // Template Info
    /** Pass the updated template name to set it within the template store */
    setName(name: string): void;

    // Template Exercises
    /** Add a new template exercise by passing an exercise id which the new template exercise will be generated by */
    addTemplateExercise(exerciseId: Exercise): void;
    /** Update certain properties of the template exercise */
    updateTemplateExercise(updatedTemplateExercise: TemplateExerciseUpdate): void;
    /** Remove a template exercise and it's template sets by passing the template exercise id */
    removeTemplateExercise(templateExerciseId: string): void;
    /** Pass the updated positions to set the positions for the template exercises  */
    setTemplateExercisePositions(newPositions: Record<string, number>): void;

    // Template Sets
    /** Add a new template set by passing the template exercise id which the new template set will be generated by */
    addTemplateSet(templateSetId: string): void;
    /** Update certain properties of the template set */
    updateTemplateSet(updatedTemplateSet: TemplateSetUpdate): void;
    /** Remove a template set by passing the template set id */
    removeTemplateSet(templateSetId: string): void;

    // Utils
    /** Returns a template object that is formatted correctly for submission */
    getSubmittableTemplate(): TemplateCreate | TemplateUpdate;
  };
}

type TemplateStore = TemplateStoreState & TemplateStoreAPI;

const createTemplateStore = (initProps?: Partial<TemplateStoreProps>) => {
  let DEFAULT_PROPS: TemplateStoreState = {
    id: initProps?.id || uuidv4(),
    name: initProps?.name || 'Legs 1',
    changed: { name: false },

    isNew: !initProps?.id,

    templateExercises: {
      all: {},
      existing: new Set(),
      new: new Set(),
      updated: new Set(),
      deleted: new Set(),
      filters: { byExerciseId: {} },
    },
    templateSets: {
      all: {},
      existing: new Set(),
      new: new Set(),
      updated: new Set(),
      deleted: new Set(),
      filters: { byTemplateExerciseId: {} },
    },
  };

  DEFAULT_PROPS = produce(DEFAULT_PROPS, (draft) => {
    if (initProps?.templateExercises) {
      const sortedTemplateExercises = initProps.templateExercises.sort((a, b) => a.position - b.position);
      for (let i = 0; i < sortedTemplateExercises.length; i++) {
        const { position, ...templateExercise } = sortedTemplateExercises[i]!;

        // Add template exercise to the all object
        draft.templateExercises.all[templateExercise.id] = { ...templateExercise, position: i };

        const { id, exerciseId } = templateExercise;

        // Add the template exercise to the existing array
        draft.templateExercises.existing.add(id);

        // Add template exercise to it's byExerciseId filter
        if (!draft.templateExercises.filters.byExerciseId[exerciseId]) {
          draft.templateExercises.filters.byExerciseId[exerciseId] = new Set();
        }
        draft.templateExercises.filters.byExerciseId[exerciseId]?.add(id);

        // If position is incorrect, add it to the updated template exercises to be fixed
        if (position !== i) draft.templateExercises.updated.add(id);
      }
    }
    if (initProps?.templateSets) {
      for (const templateSet of initProps.templateSets) {
        // Add template set to the all object
        draft.templateSets.all[templateSet.id] = templateSet;

        const { id, templateExerciseId } = templateSet;

        // Add the template set to the existing array
        draft.templateSets.existing.add(id);

        // Add template set to it's byTemplateExerciseId object
        if (!draft.templateSets.filters.byTemplateExerciseId[templateExerciseId]) {
          draft.templateSets.filters.byTemplateExerciseId[templateExerciseId] = new Set();
        }
        draft.templateSets.filters.byTemplateExerciseId[templateExerciseId]?.add(id);
      }
    }
  });

  return createStore(
    immer<TemplateStore>((set, get) => ({
      ...DEFAULT_PROPS,

      api: {
        // Template Info
        setName: (name) =>
          set((template) => {
            template.name = name;
            if (!template.changed.name) template.changed.name = true;
          }),

        // Template Exercises
        addTemplateExercise: (exercise) => {
          const templateExerciseId = uuidv4();
          set((template) => {
            const user = getAuthSafeUser();
            const { id: exerciseId } = exercise;

            const templateExercise: TemplateExerciseWithExercise = {
              id: templateExerciseId,
              exerciseId,
              exercise,
              templateId: template.id,
              createdAt: new Date(),
              notes: '',
              userId: user.id,
              position: Object.keys(template.templateExercises.all).length,
            };

            // Add the Template Exercise to the all object and the new array
            template.templateExercises.all[templateExercise.id] = templateExercise;
            template.templateExercises.new.add(templateExercise.id);

            // Add the Template Exercise id to the byExerciseId object
            if (!template.templateExercises.filters.byExerciseId[exerciseId]) {
              template.templateExercises.filters.byExerciseId[exerciseId] = new Set();
            }
            template.templateExercises.filters.byExerciseId[exerciseId]?.add(templateExercise.id);
          });

          // Create 3 sets for the new exercise
          for (let i = 0; i < 3; i++) {
            get().api.addTemplateSet(templateExerciseId);
          }
        },
        updateTemplateExercise: (updatedTemplateExercise) =>
          set((template) => {
            const { id, ...changes } = updatedTemplateExercise;
            if (template.templateExercises.all[id]) {
              template.templateExercises.all[id] = {
                ...template.templateExercises.all[id]!,
                ...changes,
              };
            }
          }),
        removeTemplateExercise: (templateExerciseId) => {
          set((template) => {
            const templateExercise = template.templateExercises.all[templateExerciseId];

            if (!templateExercise) return;

            // If template exercise exists in the db, mark it for deletion
            if (template.templateExercises.existing.has(templateExerciseId)) {
              template.templateExercises.existing.delete(templateExerciseId);
              template.templateExercises.deleted.add(templateExerciseId);
            }

            // Update the positions of the template exercises after this one
            for (const id in template.templateExercises.all) {
              const otherTemplateExercise = template.templateExercises.all[id];
              if (otherTemplateExercise && otherTemplateExercise.position > templateExercise.position) {
                otherTemplateExercise.position--;
              }
            }

            // Remove the template exercise
            template.templateExercises.filters.byExerciseId[templateExercise.exerciseId]?.delete(templateExerciseId);
            delete template.templateExercises.all[templateExerciseId];
          });

          // Remove the template sets associated with this template exercise
          const templateExerciseSetIds = get().templateSets.filters.byTemplateExerciseId[templateExerciseId] ?? null;
          if (templateExerciseSetIds) {
            for (const templateSetId of templateExerciseSetIds) {
              get().api.removeTemplateSet(templateSetId);
            }
          }
        },
        setTemplateExercisePositions: (templateExercisePositions) =>
          set((template) => {
            for (const id in templateExercisePositions) {
              const templateExercise = template.templateExercises.all[id];
              if (templateExercise && templateExercise.position !== templateExercisePositions[id]) {
                template.templateExercises.all[id]!.position = templateExercisePositions[id]!;
                template.templateExercises.updated.add(id);
              }
            }
          }),

        // Template Sets
        addTemplateSet: (templateExerciseId) =>
          set((template) => {
            const user = getAuthSafeUser();
            const templateSet: TemplateSet = {
              id: uuidv4(),
              createdAt: new Date(),
              templateId: template.id,
              templateExerciseId,
              type: 'working',
              reps: '',
              userId: user.id,
              position: Object.keys(template.templateSets.all).length,
            };

            // Add the Template Set to the all object and the new array
            template.templateSets.all[templateSet.id] = templateSet;
            template.templateSets.new.add(templateSet.id);

            // Add the Template Set id to the byTemplateExerciseId object
            if (!template.templateSets.filters.byTemplateExerciseId[templateExerciseId]) {
              template.templateSets.filters.byTemplateExerciseId[templateExerciseId] = new Set();
            }
            template.templateSets.filters.byTemplateExerciseId[templateExerciseId]?.add(templateSet.id);
          }),
        updateTemplateSet: (updatedTemplateSet) =>
          set((template) => {
            const { id, ...changes } = updatedTemplateSet;

            if (template.templateSets.all[id]) {
              template.templateSets.all[id] = {
                ...template.templateSets.all[id]!,
                ...changes,
              };
            }
          }),
        removeTemplateSet: (templateSetId) =>
          set((template) => {
            const templateSet = template.templateSets.all[templateSetId];

            if (!templateSet) return;

            // If template set exists in the db, mark it for deletion
            if (template.templateSets.existing.has(templateSetId)) {
              template.templateSets.existing.delete(templateSetId);
              template.templateSets.deleted.add(templateSetId);
            }

            // Update the positions of the template sets after this one
            for (const id in template.templateSets.all) {
              const otherTemplateSet = template.templateSets.all[id];
              if (otherTemplateSet && otherTemplateSet.position > templateSet.position) {
                otherTemplateSet.position--;
              }
            }

            // Remove the template set
            template.templateSets.filters.byTemplateExerciseId[templateSet.templateExerciseId]?.delete(templateSetId);
            delete template.templateSets.all[templateSetId];
          }),

        // Utils
        getSubmittableTemplate: () => {
          const userId = getAuthSafeUser().id;
          const template = get();

          if (template.isNew) {
            const templateCreate = {
              id: template.id,
              name: template.name,
              userId,
              templateExercises: Object.values(template.templateExercises.all).map(
                ({ exercise: _, ...templateExercise }) => templateExercise,
              ),
              templateSets: Object.values(template.templateSets.all),
            };
            return templateCreate;
          }

          const templateUpdate = {
            id: template.id,
            name: template.changed.name ? template.name : undefined,
            userId,
            templateExercises: {
              all: Object.values(template.templateExercises.all).map(
                ({ exercise: _, ...templateExercise }) => templateExercise,
              ),
              new: Array.from(template.templateExercises.new),
              updated: Array.from(template.templateExercises.updated),
              deleted: Array.from(template.templateExercises.deleted),
            },
            templateSets: {
              all: Object.values(template.templateSets.all),
              new: Array.from(template.templateSets.new),
              updated: Array.from(template.templateSets.updated),
              deleted: Array.from(template.templateSets.deleted),
            },
          };
          return templateUpdate;
        },
      },
    })),
  );
};

type CreatedTemplateStore = ReturnType<typeof createTemplateStore>;

const TemplateContext = createContext<CreatedTemplateStore | null>(null);

function useTemplateContext<T>(selector: (state: TemplateStore) => T, equalityFn?: (left: T, right: T) => boolean): T {
  const store = useContext(TemplateContext);
  if (!store) {
    throw new Error(
      // eslint-disable-next-line @typescript-eslint/quotes
      "[Template Context] A component tried to use Template Context without being a child of a TemplateProvider or TemplateProvider's store has not been initialized yet. Please fix this",
    );
  }
  return useStore(store, selector, equalityFn);
}

interface TemplateProviderProps {
  template: TemplateWithExercisesAndSets | null;
  isLoading: boolean;
}

export function TemplateProvider({ children, template, isLoading }: React.PropsWithChildren<TemplateProviderProps>) {
  const storeRef = useRef<CreatedTemplateStore>();

  useFocusEffect(
    useCallback(() => {
      return () => {
        // @ts-expect-error - This is a hack to reset the store
        storeRef.current?.setState(null);
        storeRef.current = undefined;
      };
    }, []),
  );

  if (!storeRef.current && !isLoading) {
    storeRef.current = createTemplateStore(
      template
        ? {
            id: template.id,
            name: template.name,
            templateExercises: template.templateExercises,
            templateSets: template.templateSets,
          }
        : {},
    );
  }

  return <TemplateContext.Provider value={storeRef.current || null}>{children}</TemplateContext.Provider>;
}

/** Subscribe to the value of the template API */
export const useTemplateAPI = () => useTemplateContext((s) => s.api);

// Template Info Hooks
/** Subscribe to the value of the template id */
export const useTemplateId = () => useTemplateContext((s) => s.id);

/** Subscribe to the value of the template name */
export const useTemplateName = () => useTemplateContext((s) => s.name);

/** Subscribe to the value of the template isNew variable  */
export const useTemplateIsNew = () => useTemplateContext((s) => s.isNew);

// Template Exercise Hooks
/** Subscribe to the value of the template exercises. (Ordered correctly by their position) */
export const useTemplateExercises = () =>
  useTemplateContext((s) => Object.values(s.templateExercises.all).sort((a, b) => a.position - b.position));

/** Subscribe to the template exercises that relate to the provided exercise id */
export const useTemplateExerciseIdsByExerciseId = (exerciseId: string): Set<string> | null =>
  useTemplateContext((s) => s.templateExercises.filters.byExerciseId[exerciseId] ?? null);

/** Subscribe to a template exercise's values. (Returns null if template exercise id does not exist) */
export const useTemplateExercise = (templateExerciseId: string) =>
  useTemplateContext((s) => s.templateExercises.all[templateExerciseId] ?? null);

// Template Set Hooks
/** Subscribe the template sets for the given template exercise id. (Ordered correctly by their position) */
export function useTemplateSetsByTemplateExerciseId(templateExerciseId: string): TemplateSet[] {
  const templateSets = useTemplateContext((s) => s.templateSets.all);
  const filteredTemplateSetIds = useTemplateContext(
    (s) => s.templateSets.filters.byTemplateExerciseId[templateExerciseId] ?? null,
  );

  if (!filteredTemplateSetIds) return [];

  return Object.values(templateSets)
    .filter((templateSet) => filteredTemplateSetIds.has(templateSet.id))
    .sort((a, b) => a.position - b.position);
}

/** Subscribe to a template set's values. (Returns null if template set id does not exist) */
export const useTemplateSet = (templateSetId: string) =>
  useTemplateContext((s) => s.templateSets.all[templateSetId] ?? null);
