import 'react-native-get-random-values';
import { v4 as uuidv4 } from 'uuid';
import { createContext, useCallback, useContext, useRef } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import { createStore, useStore } from 'zustand';
import { immer } from 'zustand/middleware/immer';
import produce from 'immer';
import type { Exercise, WorkoutExerciseWithExercise, WorkoutSet, WorkoutWithExercisesAndSets } from '@podium/db';
import type { WorkoutCreate, WorkoutExerciseUpdate, WorkoutSetUpdate, WorkoutUpdate } from '@podium/api';

import { getAuthSafeUser } from '../global/AuthProvider';

interface WorkoutStoreProps {
  id: string;
  name: string;
  workoutExercises: WorkoutExerciseWithExercise[];
  workoutSets: WorkoutSet[];
}

interface WorkoutStoreState {
  id: string;
  name: string;
  changed: { name: boolean };

  isNew: boolean;

  workoutExercises: {
    /** An object with all the workout exercises, including those currently existing in the db and any updated yet to be saved, as well as any newly created exercises */
    all: Record<string, WorkoutExerciseWithExercise>;
    /** An array of the workout exercise ids that exist in the db  */
    existing: Set<string>;
    /** An array of the workout exercise ids that are new  */
    new: Set<string>;
    /** An array of the workout exercise ids that have been updated */
    updated: Set<string>;
    /** An array of all the workout exercise ids that currently exist in the db but have been deleted but not saved yet */
    deleted: Set<string>;
    /** Useful filters to help access specific workout exercises quicker */
    filters: {
      /** An object of exercise ids and the array of workout exercise ids that relate to it */
      byExerciseId: Record<string, Set<string>>;
    };
  };
  workoutSets: {
    /** An object with all the workout sets, including those currently existing in the db and any updated yet to be saved, as well as any newly created sets */
    all: Record<string, WorkoutSet>;
    /** An array of the workout set ids that exist in the db  */
    existing: Set<string>;
    /** An array of the workout set ids that are new  */
    new: Set<string>;
    /** An array of the workout set ids that have been updated */
    updated: Set<string>;
    /** An array of all the workout set ids that currently exist in the db but have been deleted but not saved yet */
    deleted: Set<string>;
    /** Useful filters to help access specific workout sets quicker */
    filters: {
      /** An object of workout exercise ids and the array of workout set ids that relate to it */
      byWorkoutExerciseId: Record<string, Set<string>>;
    };
  };
}

interface WorkoutStoreAPI {
  api: {
    // Active Workout Info
    /** Pass the updated workout name to set it within the workout store */
    setName(name: string): void;

    // Workout Exercises
    /** Add a new workout exercise by passing an exercise id which the new workout exercise will be generated by */
    addWorkoutExercise(exerciseId: Exercise): void;
    /** Update certain properties of the workout exercise */
    updateWorkoutExercise(updatedWorkoutExercise: WorkoutExerciseUpdate): void;
    /** Remove a workout exercise and it's workout sets by passing the workout exercise id */
    removeWorkoutExercise(workoutExerciseId: string): void;
    /** Pass the updated positions to set the positions for the workout exercises  */
    setWorkoutExercisePositions(positions: Record<string, number>): void;

    // Workout Sets
    /** Add a new workout set by passing the workout exercise id which the new workout set will be generated by */
    addWorkoutSet(workoutExerciseId: string): void;
    /** Update certain properties of the workout set */
    updateWorkoutSet(updatedWorkoutSet: WorkoutSetUpdate): void;
    /** Remove a workout set by passing the workout set id */
    removeWorkoutSet(workoutSetId: string): void;

    // Utils
    /** Returns a workout object that is formatted correctly for submission */
    getSubmittableWorkout(): WorkoutCreate | WorkoutUpdate;
  };
}

type WorkoutStore = WorkoutStoreState & WorkoutStoreAPI;

const createWorkoutStore = (initProps?: Partial<WorkoutStoreProps>) => {
  let DEFAULT_PROPS: WorkoutStoreState = {
    id: initProps?.id || uuidv4(),
    name: initProps?.name || '',
    changed: { name: false },

    isNew: !initProps?.id,

    workoutExercises: {
      all: {},
      existing: new Set(),
      new: new Set(),
      updated: new Set(),
      deleted: new Set(),
      filters: { byExerciseId: {} },
    },
    workoutSets: {
      all: {},
      existing: new Set(),
      new: new Set(),
      updated: new Set(),
      deleted: new Set(),
      filters: { byWorkoutExerciseId: {} },
    },
  };

  DEFAULT_PROPS = produce(DEFAULT_PROPS, (draft) => {
    if (initProps?.workoutExercises) {
      const sortedWorkoutExercises = initProps.workoutExercises.sort((a, b) => a.position - b.position);
      for (let i = 0; i < sortedWorkoutExercises.length; i++) {
        const { position, ...workoutExercise } = sortedWorkoutExercises[i]!;

        // Add workout exercise to the all object
        draft.workoutExercises.all[workoutExercise.id] = { ...workoutExercise, position: i };

        const { id, exerciseId } = workoutExercise;

        // Add the workout exercise to the existing array
        draft.workoutExercises.existing.add(id);

        // Add workout exercise to it's byExerciseId filter
        if (!draft.workoutExercises.filters.byExerciseId[exerciseId]) {
          draft.workoutExercises.filters.byExerciseId[exerciseId] = new Set();
        }
        draft.workoutExercises.filters.byExerciseId[exerciseId]?.add(id);

        // If position is incorrect, add it to the updated workout exercises to be fixed
        if (position !== i) draft.workoutExercises.updated.add(id);
      }
    }
    if (initProps?.workoutSets) {
      for (const workoutSet of initProps.workoutSets) {
        // Add workout set to the all object
        draft.workoutSets.all[workoutSet.id] = workoutSet;

        const { id, workoutExerciseId } = workoutSet;

        // Add the workout set to the existing array
        draft.workoutSets.existing.add(id);

        // Add workout set to it's byWorkoutExerciseId object
        if (!draft.workoutSets.filters.byWorkoutExerciseId[workoutExerciseId]) {
          draft.workoutSets.filters.byWorkoutExerciseId[workoutExerciseId] = new Set();
        }
        draft.workoutSets.filters.byWorkoutExerciseId[workoutExerciseId]?.add(id);
      }
    }
  });

  return createStore(
    immer<WorkoutStore>((set, get) => ({
      ...DEFAULT_PROPS,

      api: {
        // Workout Info
        setName: (name) =>
          set((workout) => {
            workout.name = name;
            if (!workout.changed.name) workout.changed.name = true;
          }),

        // Workout Exercises
        addWorkoutExercise: (exercise) => {
          const workoutExerciseId = uuidv4();
          set((workout) => {
            const user = getAuthSafeUser();
            const { id: exerciseId } = exercise;

            const workoutExercise: WorkoutExerciseWithExercise = {
              id: workoutExerciseId,
              exerciseId,
              exercise,
              workoutId: workout.id,
              createdAt: new Date(),
              notes: '',
              userId: user.id,
              position: Object.keys(workout.workoutExercises.all).length,
            };

            // Add the Workout Exercise to the all object and the new array
            workout.workoutExercises.all[workoutExercise.id] = workoutExercise;
            workout.workoutExercises.new.add(workoutExercise.id);

            // Add the Workout Exercise id to the byExerciseId object
            if (!workout.workoutExercises.filters.byExerciseId[exerciseId]) {
              workout.workoutExercises.filters.byExerciseId[exerciseId] = new Set();
            }
            workout.workoutExercises.filters.byExerciseId[exerciseId]?.add(workoutExercise.id);
          });

          // Create 3 sets for the new exercise
          for (let i = 0; i < 3; i++) {
            get().api.addWorkoutSet(workoutExerciseId);
          }
        },
        updateWorkoutExercise: (updatedWorkoutExercise) =>
          set((workout) => {
            const { id, ...changes } = updatedWorkoutExercise;
            if (workout.workoutExercises.all[id]) {
              workout.workoutExercises.all[id] = {
                ...workout.workoutExercises.all[id]!,
                ...changes,
              };
            }
          }),
        removeWorkoutExercise: (workoutExerciseId) => {
          set((workout) => {
            const workoutExercise = workout.workoutExercises.all[workoutExerciseId];

            if (!workoutExercise) return;

            // If workout exercise exists in the db, mark it for deletion
            if (workout.workoutExercises.existing.has(workoutExerciseId)) {
              workout.workoutExercises.existing.delete(workoutExerciseId);
              workout.workoutExercises.deleted.add(workoutExerciseId);
            }

            // Update the positions of the workout exercises after this one
            for (const id in workout.workoutExercises.all) {
              const otherWorkoutExercise = workout.workoutExercises.all[id];
              if (otherWorkoutExercise && otherWorkoutExercise.position > workoutExercise.position) {
                otherWorkoutExercise.position--;
              }
            }

            // Remove the workout exercise
            workout.workoutExercises.filters.byExerciseId[workoutExercise.exerciseId]?.delete(workoutExerciseId);
            delete workout.workoutExercises.all[workoutExerciseId];
          });

          // Remove the workout sets associated with this workout exercise
          const workoutExerciseSetIds = get().workoutSets.filters.byWorkoutExerciseId[workoutExerciseId] ?? null;
          if (workoutExerciseSetIds) {
            for (const workoutSetId of workoutExerciseSetIds) {
              get().api.removeWorkoutSet(workoutSetId);
            }
          }
        },
        setWorkoutExercisePositions: (workoutExercisePositions) =>
          set((workout) => {
            for (const id in workoutExercisePositions) {
              const workoutExercise = workout.workoutExercises.all[id];
              if (workoutExercise && workoutExercise.position !== workoutExercisePositions[id]) {
                workout.workoutExercises.all[id]!.position = workoutExercisePositions[id]!;
                workout.workoutExercises.updated.add(id);
              }
            }
          }),

        // Workout Sets
        addWorkoutSet: (workoutExerciseId) =>
          set((workout) => {
            const user = getAuthSafeUser();
            const workoutSet: WorkoutSet = {
              id: uuidv4(),
              createdAt: new Date(),
              workoutId: workout.id,
              workoutExerciseId,
              type: 'working',
              weight: 0,
              reps: '',
              userId: user.id,
              position: Object.keys(workout.workoutSets.all).length,
            };

            // Add the Workout Set to the all object and the new array
            workout.workoutSets.all[workoutSet.id] = workoutSet;
            workout.workoutSets.new.add(workoutSet.id);

            // Add the Workout Set id to the byWorkoutExerciseId object
            if (!workout.workoutSets.filters.byWorkoutExerciseId[workoutExerciseId]) {
              workout.workoutSets.filters.byWorkoutExerciseId[workoutExerciseId] = new Set();
            }
            workout.workoutSets.filters.byWorkoutExerciseId[workoutExerciseId]?.add(workoutSet.id);
          }),
        updateWorkoutSet: (updatedWorkoutSet) =>
          set((workout) => {
            const { id, ...changes } = updatedWorkoutSet;

            if (workout.workoutSets.all[id]) {
              workout.workoutSets.all[id] = {
                ...workout.workoutSets.all[id]!,
                ...changes,
              };
            }
          }),
        removeWorkoutSet: (workoutSetId) =>
          set((workout) => {
            const workoutSet = workout.workoutSets.all[workoutSetId];

            if (!workoutSet) return;

            // If workout set exists in the db, mark it for deletion
            if (workout.workoutSets.existing.has(workoutSetId)) {
              workout.workoutSets.existing.delete(workoutSetId);
              workout.workoutSets.deleted.add(workoutSetId);
            }

            // Update the positions of the workout sets after this one
            for (const id in workout.workoutSets.all) {
              const otherWorkoutSet = workout.workoutSets.all[id];
              if (otherWorkoutSet && otherWorkoutSet.position > workoutSet.position) {
                otherWorkoutSet.position--;
              }
            }

            // Remove the workout set
            workout.workoutSets.filters.byWorkoutExerciseId[workoutSet.workoutExerciseId]?.delete(workoutSetId);
            delete workout.workoutSets.all[workoutSetId];
          }),

        // Utils
        getSubmittableWorkout: () => {
          const userId = getAuthSafeUser().id;
          const workout = get();

          if (workout.isNew) {
            const workoutCreate = {
              id: workout.id,
              name: workout.name,
              userId,
              workoutExercises: Object.values(workout.workoutExercises.all).map(
                ({ exercise: _, ...workoutExercise }) => workoutExercise,
              ),
              workoutSets: Object.values(workout.workoutSets.all),
            };
            return workoutCreate;
          }

          const workoutUpdate = {
            id: workout.id,
            name: workout.changed.name ? workout.name : undefined,
            userId,
            workoutExercises: {
              all: Object.values(workout.workoutExercises.all).map(
                ({ exercise: _, ...workoutExercise }) => workoutExercise,
              ),
              new: Array.from(workout.workoutExercises.new),
              updated: Array.from(workout.workoutExercises.updated),
              deleted: Array.from(workout.workoutExercises.deleted),
            },
            workoutSets: {
              all: Object.values(workout.workoutSets.all),
              new: Array.from(workout.workoutSets.new),
              updated: Array.from(workout.workoutSets.updated),
              deleted: Array.from(workout.workoutSets.deleted),
            },
          };
          return workoutUpdate;
        },
      },
    })),
  );
};

type CreatedWorkoutStore = ReturnType<typeof createWorkoutStore>;

const WorkoutContext = createContext<CreatedWorkoutStore | null>(null);

function useWorkoutContext<T>(selector: (state: WorkoutStore) => T, equalityFn?: (left: T, right: T) => boolean): T {
  const store = useContext(WorkoutContext);
  if (!store) {
    throw new Error(
      // eslint-disable-next-line @typescript-eslint/quotes
      "[Workout Context] A component tried to use Workout Context without being a child of a WorkoutProvider or WorkoutProvider's store has not been initialized yet. Please fix this",
    );
  }
  return useStore(store, selector, equalityFn);
}

interface WorkoutProviderProps {
  workout: WorkoutWithExercisesAndSets | null;
  isLoading: boolean;
}

export function WorkoutProvider({ children, workout, isLoading }: React.PropsWithChildren<WorkoutProviderProps>) {
  const storeRef = useRef<CreatedWorkoutStore>();

  useFocusEffect(
    useCallback(() => {
      return () => {
        // @ts-expect-error - This is a hack to reset the store
        storeRef.current?.setState(null);
        storeRef.current = undefined;
      };
    }, []),
  );

  if (!storeRef.current && !isLoading) {
    storeRef.current = createWorkoutStore(
      workout
        ? {
            id: workout.id,
            name: workout.name,
            workoutExercises: workout.workoutExercises,
            workoutSets: workout.workoutSets,
          }
        : {},
    );
  }

  return <WorkoutContext.Provider value={storeRef.current || null}>{children}</WorkoutContext.Provider>;
}

/** Subscribe to the value of the workout API */
export const useWorkoutAPI = () => useWorkoutContext((s) => s.api);

// Workout Info Hooks
/** Subscribe to the value of the workout id */
export const useWorkoutId = () => useWorkoutContext((s) => s.id);
/** Subscribe to the value of the workout name */
export const useWorkoutName = () => useWorkoutContext((s) => s.name);
/** Subscribe to the value of the workout isNew variable */
export const useWorkoutIsNew = () => useWorkoutContext((s) => s.isNew);

// Workout Exercise Hooks
/** Subscribe to the value of the workout exercises. (Ordered correctly by their position) */
export const useWorkoutExercises = () =>
  useWorkoutContext((s) => Object.values(s.workoutExercises.all).sort((a, b) => a.position - b.position));
