import { Text } from 'react-native';
import 'react-native-get-random-values';
import { v4 as uuidv4 } from 'uuid';
import { createStore, useStore } from 'zustand';
import { immer } from 'zustand/middleware/immer';
import produce from 'immer';

import { createContext, useContext, useRef } from 'react';
import type { SharedValue } from 'react-native-reanimated';
import { Prisma } from '@podium/db';
import type { TemplateExercise, TemplateSet } from '@podium/db';
import { trpc } from '@/utils/trpc';
import { SafeAreaView } from '@/components/ui/layout/SafeAreaView';
import { Loader } from '@/components/ui/feedback/Loader';
import { useSession } from '@/_app';
import { useAuthSession } from '@/stores/global/auth';

type ExerciseId = string;
type TemplateId = string;
type TemplateExerciseId = string;
type TemplateSetId = string;

type Position = number;

type NewTemplateExercise = Omit<TemplateExercise, 'createdAt' | 'position' | 'userId'>;
type ChangeableTemplateExerciseProperties = Partial<Pick<TemplateExercise, 'notes'>>;
type UpdatedTemplateExercise = ChangeableTemplateExerciseProperties & { id: TemplateExerciseId };

type NewTemplateSet = Omit<TemplateSet, 'position' | 'createdAt' | 'userId'>;
type ChangeableTemplateSetProperties = Partial<Pick<TemplateSet, 'reps' | 'type'>>;
type UpdatedTemplateSet = ChangeableTemplateExerciseProperties & { id: TemplateSetId };

type TemplateExercisePositions = Record<TemplateExerciseId, Position>;
type TemplateSetPositions = Record<TemplateExerciseId, Record<TemplateSetId, Position>>;

interface TemplateStoreProps {
  id: TemplateId;
  templateExercises: TemplateExercise[];
  templateSets: TemplateSet[];
}

interface TemplateStoreState {
  id: TemplateId;
  name: string;
  templateExercise: {
    /** An array of all the template exercises that currently exist in the db for this template and haven't been modified by the user */
    existing: Array<TemplateExerciseId>;
    /** An object of all the new template exercises created  */
    new: Record<TemplateExerciseId, NewTemplateExercise>;
    /** An object of all the existing template exercises that have been modified */
    updated: Record<TemplateExerciseId, UpdatedTemplateExercise>;
    /** An array of all the template exercise ids which currently exist in the db but the user has deleted but not submitted yet. */
    deleted: Array<TemplateExerciseId>;
    /** An object of exercise ids and the array of template exercise ids that relate to it */
    byExerciseId: Record<ExerciseId, Array<TemplateExerciseId>>;
    /** An object of the current order of all the exercises */
    positions: TemplateExercisePositions;
  };
  templateSet: {
    /** An array of all the template sets that currently exist in the db for this template and haven't been modified by the user */
    existing: Array<TemplateSetId>;
    /** An object of all the new template sets created  */
    new: Record<TemplateSetId, NewTemplateSet>;
    /** An object of all the existing template sets that have been modified */
    updated: Record<TemplateSetId, UpdatedTemplateSet>;
    /** An array of all the template set ids which currently exist in the db but the user has deleted but not submitted yet. */
    deleted: Array<TemplateSetId>;
    /** An object of template exercise ids and the array of template set ids that relate to it */
    byTemplateExerciseId: Record<TemplateExerciseId, Array<TemplateSetId>>;
    /** An object of the current order of the template sets grouped by their template exercise id */
    positions: TemplateSetPositions;
  };
}

interface TemplateStoreAPI {
  api: {
    // Template Info
    /** Pass the new template id to update it within the template store */
    setId(id: string): void;
    /** Pass the updated template name to set it within the template store */
    setName(name: string): void;

    // Template Exercises
    /** Add a new template exercise by passing an exercise id which the new template exercise will be generated by */
    addTemplateExercise(exerciseId: ExerciseId): void;
    /** Update certain properties of the template exercise */
    updateTemplateExercise(templateExerciseId: TemplateExerciseId, changes: ChangeableTemplateExerciseProperties): void;
    /** Remove a template exercise and it's template sets by passing the template exercise id */
    removeTemplateExercise(templateExerciseId: TemplateExerciseId): void;
    /** Pass the updated positions to set the positions for the template exercises  */
    syncTemplateExercisePositions(positions: TemplateExercisePositions): void;

    // Template Sets
    /** Add a new template set by passing the template exercise id which the new template set will be generated by */
    addTemplateSet(templateExerciseId: TemplateExerciseId): void;
    /** Update certain properties of the template set */
    updateTemplateSet(templateSetId: TemplateSetId, changes: ChangeableTemplateSetProperties): void;
    /** Remove a template set by passing the template set id */
    removeTemplateSet(templateSetId: TemplateSetId): void;
  };
}

type TemplateStore = TemplateStoreState & TemplateStoreAPI;

const createTemplateStore = (initProps?: Partial<TemplateStoreProps>) => {
  let DEFAULT_PROPS: TemplateStoreState = {
    id: initProps?.id || uuidv4(),
    name: 'Legs 1',
    templateExercise: { existing: [], new: {}, updated: {}, deleted: [], byExerciseId: {}, positions: {} },
    templateSet: { existing: [], new: {}, updated: {}, deleted: [], byTemplateExerciseId: {}, positions: {} },
  };

  DEFAULT_PROPS = produce(DEFAULT_PROPS, (draft) => {
    if (initProps?.templateExercises) {
      for (const templateExercise of initProps.templateExercises) {
        const { id, exerciseId, position } = templateExercise;

        // Add template exercise to the existing object
        draft.templateExercise.existing.push(id);

        // Add template exercise to it's byExerciseId object
        if (!draft.templateExercise.byExerciseId[exerciseId]) {
          draft.templateExercise.byExerciseId[exerciseId] = [];
        }
        draft.templateExercise.byExerciseId[exerciseId].push(id);

        // Define the position of the existing template exercise
        draft.templateExercise.positions[id] = position;
      }
    }
    if (initProps?.templateSets) {
      for (const templateSet of initProps.templateSets) {
        const { id, templateExerciseId, position } = templateSet;

        // Add template set to the existing object
        draft.templateSet.existing.push(id);

        // Add template set to it's byTemplateExerciseId object
        if (!draft.templateSet.byTemplateExerciseId[templateExerciseId]) {
          draft.templateSet.byTemplateExerciseId[templateExerciseId] = [];
        }
        draft.templateSet.byTemplateExerciseId[templateExerciseId].push(id);

        // Define the position of the template set
        if (!draft.templateSet.positions[templateExerciseId]) {
          draft.templateSet.positions[templateExerciseId] = {};
        }
        draft.templateSet.positions[templateExerciseId][id] = position;
      }
    }
  });

  return createStore(
    immer<TemplateStore>((set, get) => ({
      ...DEFAULT_PROPS,

      api: {
        // Template Info
        setId: (id) => set({ id }),
        setName: (name) => set({ name }),

        // Template Exercises
        addTemplateExercise: (exerciseId) => {
          const templateExerciseId = uuidv4();
          set((template) => {
            const templateExercise: NewTemplateExercise = {
              id: templateExerciseId,
              exerciseId,
              templateId: template.id,
              notes: '',
            };

            // Add the Template Exercise id to the byExerciseId object
            if (!template.templateExercise.byExerciseId[exerciseId]) {
              template.templateExercise.byExerciseId[exerciseId] = [];
            }
            template.templateExercise.byExerciseId[exerciseId].push(templateExercise.id);

            // Add the Template Exercise to the new Template Exercises object.
            template.templateExercise.new[templateExercise.id] = templateExercise;

            // Add Template Exercise to positions
            template.templateExercise.positions[templateExercise.id] = Object.keys(
              template.templateExercise.positions,
            ).length;
          });
          // Create 3 sets for the new exercise
          for (let i = 0; i < 1; i++) {
            get().api.addTemplateSet(templateExerciseId);
          }
        },
        updateTemplateExercise: (templateExerciseId, changes) =>
          set((template) => {
            const isExisting = !!template.templateExercise.existing.includes(templateExerciseId);
            const isNew = !!template.templateExercise.new[templateExerciseId];
            const isUpdated = !!template.templateExercise.updated[templateExerciseId];

            if (isExisting) {
              template.templateExercise.existing = template.templateExercise.existing.filter(
                (id) => id !== templateExerciseId,
              );
              template.templateExercise.updated[templateExerciseId] = { id: templateExerciseId, ...changes };
            }

            if (isNew) {
              template.templateExercise.new[templateExerciseId] = {
                ...template.templateExercise.new[templateExerciseId],
                ...changes,
              };
            }

            if (isUpdated) {
              template.templateExercise.updated[templateExerciseId] = {
                ...template.templateExercise.updated[templateExerciseId],
                ...changes,
              };
            }
          }),
        removeTemplateExercise: (templateExerciseId) => {
          set((template) => {
            const isExisting = !!template.templateExercise.existing.includes(templateExerciseId);
            const isNew = !!template.templateExercise.new[templateExerciseId];
            const isUpdated = !!template.templateExercise.updated[templateExerciseId];

            if (isExisting) {
              template.templateExercise.existing = template.templateExercise.existing.filter(
                (id) => id !== templateExerciseId,
              );
              template.templateExercise.deleted.push(templateExerciseId);
            }

            if (isNew) {
              const exerciseId = template.templateExercise.new[templateExerciseId].exerciseId;
              delete template.templateExercise.new[templateExerciseId];
              template.templateExercise.byExerciseId[exerciseId] = template.templateExercise.byExerciseId[
                exerciseId
              ].filter((id) => id !== templateExerciseId);
            }

            if (isUpdated) {
              delete template.templateExercise.updated[templateExerciseId];
              template.templateExercise.deleted.push(templateExerciseId);
            }

            // Remove template exercise from Template Exercise positions
            const newPositions: TemplateExercisePositions = {};
            const swapped = Object.entries(template.templateExercise.positions).map(([key, value]) => [value, key]);
            const ids = swapped
              .sort()
              .map(([_, value]) => value as string)
              .filter((id) => id !== templateExerciseId);

            ids.forEach((id, index) => {
              newPositions[id] = index;
            });
            template.templateExercise.positions = newPositions;
          });

          // Remove the template sets associated with this template exercise
          const templateExerciseSetIds = get().templateSet.byTemplateExerciseId[templateExerciseId] ?? null;
          if (templateExerciseSetIds) {
            for (const templateSetId of templateExerciseSetIds) {
              get().api.removeTemplateSet(templateSetId);
            }
          }
        },
        syncTemplateExercisePositions: (positions) =>
          set((template) => {
            template.templateExercise.positions = positions;
          }),

        // Template Sets
        addTemplateSet: (templateExerciseId) =>
          set((template) => {
            const templateSet: NewTemplateSet = {
              id: uuidv4(),
              templateId: template.id,
              templateExerciseId,
              type: 'working',
              reps: '',
            };

            // Add the Template Set id to the byTemplateExerciseId object
            if (!template.templateSet.byTemplateExerciseId[templateExerciseId]) {
              template.templateSet.byTemplateExerciseId[templateExerciseId] = [];
            }
            template.templateSet.byTemplateExerciseId[templateExerciseId].push(templateSet.id);

            // Add the Template Set to the new Template Sets object.
            template.templateSet.new[templateSet.id] = templateSet;

            // Add the new template set to the positions object of its template exercise
            if (!template.templateSet.positions[templateExerciseId]) {
              template.templateSet.positions[templateExerciseId] = {};
            }
            template.templateSet.positions[templateExerciseId][templateSet.id] = Object.keys(
              template.templateSet.positions[templateExerciseId],
            ).length;
          }),
        updateTemplateSet: (templateSetId, changes) =>
          set((template) => {
            const isExisting = !!template.templateSet.existing.includes(templateSetId);
            const isNew = !!template.templateSet.new[templateSetId];
            const isUpdated = !!template.templateSet.updated[templateSetId];

            if (isExisting) {
              template.templateSet.existing = template.templateSet.existing.filter((id) => id !== templateSetId);
              template.templateSet.updated[templateSetId] = { id: templateSetId, ...changes };
            }

            if (isNew) {
              template.templateSet.new[templateSetId] = {
                ...template.templateSet.new[templateSetId],
                ...changes,
              };
            }

            if (isUpdated) {
              template.templateSet.updated[templateSetId] = {
                ...template.templateSet.updated[templateSetId],
                ...changes,
              };
            }
          }),
        removeTemplateSet: (templateSetId) =>
          set((template) => {
            const isExisting = !!template.templateSet.existing.includes(templateSetId);
            const isNew = !!template.templateSet.new[templateSetId];
            const isUpdated = !!template.templateSet.updated[templateSetId];
            const templateExerciseId = template.templateSet.new[templateSetId].templateExerciseId;

            if (isExisting) {
              template.templateSet.existing = template.templateSet.existing.filter((id) => id !== templateSetId);
              template.templateSet.deleted.push(templateSetId);
            }

            if (isNew) {
              delete template.templateSet.new[templateSetId];
              template.templateSet.byTemplateExerciseId[templateExerciseId] = template.templateSet.byTemplateExerciseId[
                templateExerciseId
              ].filter((id) => id !== templateSetId);
            }

            if (isUpdated) {
              delete template.templateSet.updated[templateSetId];
              template.templateSet.deleted.push(templateSetId);
            }

            // Update all the template set positions of the same template exercise
            const newPositions: Record<TemplateSetId, Position> = {};
            const swapped = Object.entries(template.templateSet.positions[templateExerciseId]).map(([key, value]) => [
              value,
              key,
            ]);
            const ids = swapped
              .sort()
              .map(([_, value]) => value as string)
              .filter((id) => id !== templateSetId);

            ids.forEach((id, index) => {
              newPositions[id] = index;
            });
            template.templateSet.positions[templateExerciseId] = newPositions;
          }),
      },
    })),
  );
};

type CreatedTemplateStore = ReturnType<typeof createTemplateStore>;

const TemplateContext = createContext<CreatedTemplateStore | null>(null);

function useTemplateContext<T>(selector: (state: TemplateStore) => T, equalityFn?: (left: T, right: T) => boolean): T {
  const store = useContext(TemplateContext);
  if (!store) {
    throw new Error(
      '[Template Context] A component tried to use Template Context without being a child of a TemplateProvider',
    );
  }
  return useStore(store, selector, equalityFn);
}

interface TemplateProviderProps {
  id: string | null;
}

export function TemplateProvider({ children, id }: React.PropsWithChildren<TemplateProviderProps>) {
  const templateId = id ?? uuidv4();
  const queriesEnabled = typeof id === 'string';

  const storeRef = useRef<CreatedTemplateStore>();

  if (!storeRef.current) {
    storeRef.current = createTemplateStore({ id: templateId });
  }

  //   const {
  //     data: template,
  //     isLoading: isTemplateLoading,
  //     isError: isTemplateError,
  //   } = trpc.templates.byId.useQuery({ id: templateId }, { enabled: queriesEnabled });

  //   if (queriesEnabled && (isTemplateLoading || isTemplateExercisesLoading || isTemplateSetsLoading)) {
  //     return (
  //       <SafeAreaView style={{ alignItems: 'center', justifyContent: 'center' }}>
  //         <Loader />
  //         <Text>Template Provider Loading...</Text>
  //       </SafeAreaView>
  //     );
  //   }

  //   if (isTemplateError || isTemplateExercisesError || isTemplateSetsError) {
  //     return (
  //       <SafeAreaView style={{ alignItems: 'center', justifyContent: 'center' }}>
  //         <Text>Oh no... An error occurred!</Text>
  //       </SafeAreaView>
  //     );
  //   }

  return <TemplateContext.Provider value={storeRef.current}>{children}</TemplateContext.Provider>;
}

export const useTemplateAPI = () => useTemplateContext((s) => s.api);

// Template Info
export const useTemplateId = () => useTemplateContext((s) => s.id);
export const useTemplateName = () => useTemplateContext((s) => s.name);

// Template Exercise
/** Returns an array of all the template exercise ids in order of their positions */
export function useTemplateExerciseIds() {
  const positions = useTemplateContext((s) => s.templateExercise.positions);
  const swapped = Object.entries(positions).map(([key, value]) => [value, key]);
  const ids = swapped.sort().map(([_, value]) => value as string);
  return ids;
}
/** Returns all the given template sets that relate to the provided exercise id */
export function useTemplateExercisesIdsByExerciseId(exerciseId: ExerciseId): TemplateExerciseId[] | null {
  const templateExercises = useTemplateContext((s) => s.templateExercise.byExerciseId[exerciseId] ?? null);
  return templateExercises;
}

/** Returns the full template exercise of the given template exercise id or null if that id does not exist */
export function useTemplateExercise(templateExerciseId: TemplateExerciseId) {
  const newTemplateExercise: NewTemplateExercise | null = useTemplateContext(
    (s) => s.templateExercise.new[templateExerciseId] ?? null,
  );
  const updatedTemplateExercise: UpdatedTemplateExercise | null = useTemplateContext(
    (s) => s.templateExercise.updated[templateExerciseId] ?? null,
  );

  const {
    data: templateExercise,
    isLoading: isTemplateExerciseLoading,
    isError: isTemplateExerciseError,
  } = trpc.templateExercise.byId.useQuery(
    { id: templateExerciseId },
    { enabled: !updatedTemplateExercise && !newTemplateExercise },
  );

  const {
    data: exercise,
    isLoading: isExerciseLoading,
    isError: isExerciseError,
  } = trpc.exercise.byId.useQuery(
    { id: newTemplateExercise.exerciseId || updatedTemplateExercise.exerciseId },
    { enabled: !!newTemplateExercise || !!updatedTemplateExercise },
  );

  if (!updatedTemplateExercise && !newTemplateExercise) {
    return {
      templateExercise,
      isLoading: isTemplateExerciseLoading,
      isError: isTemplateExerciseError,
    };
  }

  return {
    templateExercise: {
      ...newTemplateExercise,
      ...updatedTemplateExercise,
      exercise,
    },
    isLoading: isExerciseLoading,
    isError: isExerciseError,
  };
}

/** Returns the template exercise positions object from the store */
export const useTemplateExercisePositions = () => useTemplateContext((s) => s.templateExercise.positions);

// Template Sets
/** Returns all the template sets. **NOTE: Not in position order** */
export function useTemplateSetIds() {
  const existingTemplateSets = useTemplateContext((s) => s.templateSet.existing);
  const newTemplateSets = useTemplateContext((s) => s.templateSet.new);
  const updatedTemplateSets = useTemplateContext((s) => s.templateSet.updated);

  return [...existingTemplateSets, ...Object.keys(newTemplateSets), ...Object.keys(updatedTemplateSets)];
}

/** Returns the template sets for the given template exercise id in order of their position */
export function useTemplateSetIdsByTemplateExerciseId(templateExerciseId: TemplateExerciseId): TemplateSetId[] | null {
  const positions = useTemplateContext((s) => s.templateSet.positions[templateExerciseId] ?? null);
  if (!positions) return null;
  const swapped = Object.entries(positions).map(([key, value]) => [value, key]);
  const ids = swapped.sort().map(([_, value]) => value as string);
  return ids;
}

/** Returns the full template set or null if that id does not exist  */
export function useTemplateSet(templateSetId: TemplateSetId) {
  const updateTemplateSet = useTemplateContext((s) => s.api.updateTemplateSet);
  const setTemplateSet = (changes: ChangeableTemplateSetProperties) => updateTemplateSet(templateSetId, changes);
  const newTemplateSet: NewTemplateSet | null = useTemplateContext((s) => s.templateSet.new[templateSetId] ?? null);
  const updatedTemplateSet: UpdatedTemplateSet | null = useTemplateContext(
    (s) => s.templateSet.updated[templateSetId] ?? null,
  );

  const {
    data: templateSet,
    isLoading: isTemplateSetLoading,
    isError: isTemplateSetError,
  } = trpc.templateSet.byId.useQuery({ id: templateSetId }, { enabled: !updatedTemplateSet && !newTemplateSet });

  if (!updatedTemplateSet && !newTemplateSet) {
    return {
      templateSet,
      isLoading: isTemplateSetLoading,
      isError: isTemplateSetError,
      setTemplateSet,
    };
  }

  if (newTemplateSet || updatedTemplateSet) {
    return {
      templateSet: {
        ...newTemplateSet,
        ...updatedTemplateSet,
      },
      isLoading: false,
      isError: false,
      setTemplateSet,
    };
  }

  return { templateSet: null, isLoading: false, isError: false, setTemplateSet: () => {} };
}

/** Returns all the necessary information about the template and its exercises and sets for submission  */
export function useTemplateSubmissionInformation() {
  const userId = useAuthSession()?.user.id;

  if (!userId) {
    throw new Error(
      '[useTemplateSubmissionInformation] Hook was called without a user being logged in. Please fix this.',
    );
  }

  const templateId = useTemplateContext((s) => s.id);
  const templateName = useTemplateContext((s) => s.name);

  const templateExercisePositions = useTemplateContext((s) => s.templateExercise.positions);

  const templateExerciseNew = useTemplateContext((s) => s.templateExercise.new);
  const submittableTemplateExerciseNew: Record<TemplateExerciseId, Omit<TemplateExercise, 'createdAt'>> = {};
  for (const templateExerciseId in templateExerciseNew) {
    submittableTemplateExerciseNew[templateExerciseId] = {
      ...templateExerciseNew[templateExerciseId],
      position: templateExercisePositions[templateExerciseId],
      userId,
    };
  }

  const templateExerciseUpdated = useTemplateContext((s) => s.templateExercise.updated);
  const templateExerciseDeleted = useTemplateContext((s) => s.templateExercise.deleted);

  const templateSetPositions = useTemplateContext((s) => s.templateSet.positions);
  const templateSetNew = useTemplateContext((s) => s.templateSet.new);
  const submittableTemplateSetNew: Record<TemplateSetId, Omit<TemplateSet, 'createdAt'>> = {};
  for (const templateSetId in templateSetNew) {
    const templateSet = templateSetNew[templateSetId];
    submittableTemplateSetNew[templateSetId] = {
      ...templateSet,
      position: templateSetPositions[templateSet.templateExerciseId][templateSetId],
      userId,
    };
  }
  const templateSetUpdated = useTemplateContext((s) => s.templateSet.updated);
  const templateSetDeleted = useTemplateContext((s) => s.templateSet.deleted);

  return {
    id: templateId,
    name: templateName,

    templateExercise: {
      new: submittableTemplateExerciseNew,
      updated: templateExerciseUpdated,
      deleted: templateExerciseDeleted,
    },

    templateSet: {
      new: submittableTemplateSetNew,
      updated: templateSetUpdated,
      deleted: templateSetDeleted,
    },
  };
}
